//Get list customer
export const GET_LIST_CUSTOMER_PENDING = 'GET_LIST_CUSTOMER_PENDING';
export const GET_LIST_CUSTOMER_SUCCESSFULLY = 'GET_LIST_CUSTOMNER_SUCCESSFULLY';
export const GET_LIST_CUSTOMER_FAILED = 'GET_LIST_CUSTOMNER_FAILED';
export const RESET_LIST_CUSTOMER = 'RESET_LIST_CUSTOMER';

//Get customer infomation
export const PENDING_GET_CUSTOMER_INFOMATION =
    'PENDING_GET_CUSTOMER_INFOMATION';
export const GET_CUSTOMER_INFOMATION_SUCCESSFULLY =
    'GET_CUSTOMER_INFOMATION_SUCCESSFULLY';
export const GET_CUSTOMER_INFOMATION_FAILED = 'GET_CUSTOMER_INFOMATION_FAILED';
export const RESET_CUSTOMER_INFOMATION = 'RESET_CUSTOMER_INFOMATION';

//Edit customer infomation
export const PENDING_EDIT_CUSTOMER = 'PENDING_EDIT_CUSTOMER';
export const EDIT_CUSTOMER_SUCCESSFULLY = 'EDIT_CUSTOMER_SUCCESSFULLY';
export const EDIT_CUSTOMER_FAILED = 'EDIT_CUSTOMER_FAILED';
export const RESET_EDIT_CUSTOMER_MESSAGE = 'RESET_CUSTOMER_MESSAGE';

//Add customer infomation
export const PENDING_ADD_CUSTOMER = 'PENDING_ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESSFULLY = 'ADD_CUSTOMER_SUCCESSFULLY';
export const ADD_CUSTOMER_FAILED = 'ADD_CUSTOMER_FAILED';
export const RESET_ADD_CUSTOMER_MESSAGE = 'RESET_ADD_CUSTOMER_MESSAGE';

//Delete customer infomation
export const PENDING_DELETE_CUSTOMER = 'PENDING_DELETE_CUSTOMER';
export const DELETE_CUSTOMER_SUCCESSFULLY = 'DELETE_CUSTOMER_SUCCESSFULLY';
export const DELETE_CUSTOMER_FAILED = 'DELETE_CUSTOMER_FAILED';
export const RESET_DELETE_CUSTOMER_MESSAGE = 'RESET_DELETE_CUSTOMER_MESSAGE';
