export const GET_LIST_CUSTOMER_PENDING = 'GET_LIST_CUSTOMER_PENDING';
export const GET_LIST_CUSTOMER_SUCCESSFULLY = 'GET_LIST_CUSTOMNER_SUCCESSFULLY';
export const GET_LIST_CUSTOMER_FAILED = 'GET_LIST_CUSTOMNER_FAILED';
export const RESET_LIST_CUSTOMER = 'RESET_LIST_CUSTOMER';
