//Get list product
export const PENDING_GET_LIST_PRODUCT = 'PENDING_GET_LIST_PRODUCT';
export const GET_LIST_PRODUCT_SUCCESSFULLY = 'GET_LIST_PRODUCT_SUCCESSFULLY';
export const GET_LIST_PRODUCT_FAILED = 'GET_LIST_PRODUCT_FAILED';
export const RESET_LIST_PRODUCT = 'RESET_LIST_PRODUCT';
